name: dash_todo_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  dartz: ^0.10.1
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  intl: any
  responsive_framework: ^1.5.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
